teleop: 0
velocity_control: 0

# Here we use the JOINT names instead of the
# motor controller names from gummi_dynamixel.

joints:
  shoulder_yaw:
    effort: 0.6
    gradual_startup_position: -0.05
    gradual_startup_time: 1.0
    antagonist: True
  shoulder_roll:
    effort: 0.6
    gradual_startup_position: -0.25
    gradual_startup_time: 1.0
    antagonist: True
  shoulder_pitch:
    effort: 0.6
    gradual_startup_position: 0.25
    gradual_startup_time: 1.0
    antagonist: True
  elbow:
    effort: 0.6
    gradual_startup_position: -0.6
    gradual_startup_time: 1.0
    antagonist: True
  # antagonist: False => direct driven joint
  upperarm_roll:
    effort: 1.0
    gradual_startup_position: 0
    gradual_startup_time: 1.0
    antagonist: False
  forearm_roll:
    effort: 1.0
    gradual_startup_position: 0
    gradual_startup_time: 1.0
    antagonist: False
  wrist_pitch:
    effort: 1.0
    gradual_startup_position: 0
    gradual_startup_time: 1.0
    antagonist: False
  # gripper:
  #   effort: 1.0
  #   gradual_startup_position: 0
  #   gradual_startup_time: 1.0
  #   antagonist: False
